idf_component_register(
    SRCS
        "main.cpp"
        "app.cpp"
    INCLUDE_DIRS
        "."
    REQUIRES
        core
        gui
        lvgl
        ArduinoJson
        http_client_esp
        display
        input
        wifi
        time_sync
        web_server
        storage
        board
        www_store
        nvs_flash
)
